export enum SiteImage {
  background = 'https://shdw-drive.genesysgo.net/BamXrN29Jkq9HA3UyLZWEaikDa3zcVgnP6nakvrZdQ72/super-phoenix-bg.jpeg',
  backgroundV2 = 'https://shdw-drive.genesysgo.net/BamXrN29Jkq9HA3UyLZWEaikDa3zcVgnP6nakvrZdQ72/super-phoenix-bg-v2.jpeg',
  logoFlatV3 = 'https://shdw-drive.genesysgo.net/BamXrN29Jkq9HA3UyLZWEaikDa3zcVgnP6nakvrZdQ72/super-phoenix-flat-v3.png',
  logo = 'https://shdw-drive.genesysgo.net/BamXrN29Jkq9HA3UyLZWEaikDa3zcVgnP6nakvrZdQ72/super-phoenix-logo.png',
  logoSm = 'https://shdw-drive.genesysgo.net/BamXrN29Jkq9HA3UyLZWEaikDa3zcVgnP6nakvrZdQ72/super-phoenix-logo-sm.png',
  logoFlat = 'https://shdw-drive.genesysgo.net/BamXrN29Jkq9HA3UyLZWEaikDa3zcVgnP6nakvrZdQ72/super-phoenix-flat.png',
  icon = 'https://shdw-drive.genesysgo.net/BamXrN29Jkq9HA3UyLZWEaikDa3zcVgnP6nakvrZdQ72/super-phoenix-ico.png',
  mintPageBackground = 'https://shdw-drive.genesysgo.net/BamXrN29Jkq9HA3UyLZWEaikDa3zcVgnP6nakvrZdQ72/mint_page_dark.png',
  minusIcon = '/assets/icons/minus.svg',
  plusIcon = '/assets/icons/plus.svg',
  twitterIcon = '/assets/icons/twitter.svg',
  facebookIcon = '/assets/icons/facebook.svg',
  instagramIcon = '/assets/icons/instagram.svg',
  discordIcon = '/assets/icons/discord.svg',
}
